name: CI - Build & test + Scan Trivy

on:
  push:
  pull_request:

permissions:
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Installer les dépendances
        run: npm install

      - name: Builder l'application
        run: npm run build

      - name: Lancer l'application en arrière-plan
        run: npm start &

      - name: Attendre le démarrage du serveur
        run: npx --yes wait-on http://localhost:3000

      - name: Vérifier le fonctionnement avec curl
        run: curl -I http://localhost:3000 | grep "200"

      - name: Scan Trivy (Export SARIF)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Uploader rapport SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Garantit l'envoi du rapport même en cas d'erreur
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Scan Trivy - Contrôle de sécurité
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'